"""Update User

Revision ID: 3f45d0b9a32d
Revises: e69183aba145
Create Date: 2018-10-18 21:54:48.753059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f45d0b9a32d'
down_revision = 'e69183aba145'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('phone', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('work_years', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'work_years')
    op.drop_column('user', 'phone')
    # ### end Alembic commands ###
