"""add job.is_disable

Revision ID: 621aefb9cae4
Revises: 82220c2c668a
Create Date: 2018-10-28 16:27:24.444726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '621aefb9cae4'
down_revision = '82220c2c668a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('is_disable', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job', 'is_disable')
    # ### end Alembic commands ###
