"""Delivery.Company_id

Revision ID: 77172065b570
Revises: 621aefb9cae4
Create Date: 2018-10-29 09:37:29.398421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77172065b570'
down_revision = '621aefb9cae4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('delivery', sa.Column('company_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('delivery', 'company_id')
    # ### end Alembic commands ###
